import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it } from 'vitest';
import { App } from './App';

afterEach(cleanup);

describe('App learner flow through impact analysis', () => {
  it('keeps analysis entry disabled until placement is complete, then opens the real analysis room', async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.selectOptions(screen.getByRole('combobox', { name: '미션 선택' }), 'bookmaru-library');
    await user.click(screen.getByRole('radio', { name: '접근성' }));
    await user.click(screen.getByRole('button', { name: '도시 자료실로 이동' }));
    expect(screen.getByRole('region', { name: '도시 자료실' })).toBeInTheDocument();
    await user.click(screen.getByRole('checkbox', { name: '인구' }));
    await user.click(screen.getByRole('checkbox', { name: '도로·이동 단위' }));
    await user.click(screen.getByRole('button', { name: '자료층 확인' }));
    expect(screen.getByRole('region', { name: '후보 배치판' })).toBeInTheDocument();
    const enterAnalysis = screen.getByRole('button', { name: '영향 계산' });
    expect(enterAnalysis).toBeDisabled();
    await user.click(await screen.findByRole('radio', { name: /느린 강변 터.*물빛 B2/ }));
    await user.click(screen.getByRole('button', { name: /시설 배치/ }));
    expect(screen.getByRole('button', { name: '영향 계산' })).toBeEnabled();
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(1);
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    expect(screen.getByRole('region', { name: '영향 분석실' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: '영향 계산' })).toBeEnabled();
    expect(screen.getAllByText(/평균 이동 단위:/).length).toBeGreaterThan(0);
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(2);
  });

  it('completes the resident A revision B comparison loop without a winner', async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.selectOptions(screen.getByRole('combobox', { name: '미션 선택' }), 'bookmaru-library');
    await user.click(screen.getByRole('radio', { name: '접근성' }));
    await user.click(screen.getByRole('button', { name: '도시 자료실로 이동' }));
    await user.click(screen.getByRole('checkbox', { name: '인구' }));
    await user.click(screen.getByRole('checkbox', { name: '도로·이동 단위' }));
    await user.click(screen.getByRole('button', { name: '자료층 확인' }));
    await user.click(screen.getByRole('radio', { name: /느린 강변 터.*물빛 B2/ }));
    await user.click(screen.getByRole('button', { name: /시설 배치/ }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: /평균 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: /가장 긴 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: '주민 관점표로 이동' }));
    await user.click(screen.getByRole('radio', { name: /햇살 북쪽 구역/ }));
    await user.click(screen.getByRole('button', { name: 'A안 저장' }));
    expect(screen.getByRole('button', { name: '후보 수정하여 B안 만들기' })).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: '후보 수정하여 B안 만들기' }));
    await user.click(screen.getByRole('radio', { name: /가운데 광장 터.*물빛 C3/ }));
    await user.click(screen.getByRole('button', { name: /시설 배치/ }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: /평균 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: /가장 긴 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: '주민 관점표로 이동' }));
    await user.click(screen.getByRole('radio', { name: /바람 동쪽 구역/ }));
    await user.click(screen.getByRole('button', { name: 'B안 저장' }));
    expect(screen.getByRole('heading', { name: 'A안과 B안 비교' })).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'A안 저장' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: 'B안 저장' })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: '후보 수정하여 B안 만들기' })).not.toBeInTheDocument();
    expect(screen.getByText('도서관: 느린 강변 터 (B2)')).toBeInTheDocument();
    expect(screen.getByText('2.7 이동 단위')).toBeInTheDocument();
    expect(screen.getByText('예산 토큰 3개 안에 놓기: 충족 — 배치 비용 1토큰 / 공개 한도 3토큰입니다.')).toBeInTheDocument();
    expect(screen.getByText('A안은 ___을 지키지만 ___이 불리하고, B안은 ___을 바꿉니다.')).toBeInTheDocument();
    expect(screen.queryByText(/승자|최적|정답|순위|점수/)).not.toBeInTheDocument();
  });

  it('requires an explicit opinion submission and hides the summary again after editing', async () => {
    const user = userEvent.setup();
    render(<App />);
    await user.selectOptions(screen.getByRole('combobox', { name: '미션 선택' }), 'bookmaru-library');
    await user.click(screen.getByRole('radio', { name: '접근성' }));
    await user.click(screen.getByRole('button', { name: '도시 자료실로 이동' }));
    await user.click(screen.getByRole('checkbox', { name: '인구' }));
    await user.click(screen.getByRole('checkbox', { name: '도로·이동 단위' }));
    await user.click(screen.getByRole('button', { name: '자료층 확인' }));
    await user.click(screen.getByRole('radio', { name: /느린 강변 터.*물빛 B2/ }));
    await user.click(screen.getByRole('button', { name: /시설 배치/ }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: /평균 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: /가장 긴 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: '주민 관점표로 이동' }));
    await user.click(screen.getByRole('radio', { name: /햇살 북쪽 구역/ }));
    await user.click(screen.getByRole('button', { name: 'A안 저장' }));
    await user.click(screen.getByRole('button', { name: '후보 수정하여 B안 만들기' }));
    await user.click(screen.getByRole('radio', { name: /가운데 광장 터.*물빛 C3/ }));
    await user.click(screen.getByRole('button', { name: /시설 배치/ }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: '영향 계산' }));
    await user.click(screen.getByRole('button', { name: /평균 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: /가장 긴 이동 단위/ }));
    await user.click(screen.getByRole('button', { name: '주민 관점표로 이동' }));
    await user.click(screen.getByRole('radio', { name: /바람 동쪽 구역/ }));
    await user.click(screen.getByRole('button', { name: 'B안 저장' }));
    await user.click(screen.getByRole('button', { name: '의견서 작성' }));
    expect(screen.queryByRole('heading', { name: '완성한 입지 심의 의견서' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: '의견서 작성' })).toBeEnabled();
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(1);
    await user.click(screen.getByRole('radio', { name: 'A안' }));
    await user.click(screen.getByRole('checkbox', { name: '평균 이동 단위' }));
    await user.click(screen.getByRole('checkbox', { name: '가장 긴 이동 단위' }));
    await user.click(screen.getByRole('checkbox', { name: '위험 조건' }));
    await user.selectOptions(screen.getByRole('combobox', { name: '더 불편을 살필 구역' }), 'mulbit-north');
    await user.type(screen.getByLabelText('선택안의 근거'), '접근성과 안전 자료를 함께 비교했습니다.');
    await user.type(screen.getByLabelText('예상되는 반론'), '다른 구역의 이동 부담이 커질 수 있습니다.');
    await user.type(screen.getByLabelText('보완 방법'), '단계적 안내를 함께 마련하겠습니다.');
    expect(screen.queryByRole('heading', { name: '완성한 입지 심의 의견서' })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: '의견서 작성' })).toBeEnabled();
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(1);
    await user.click(screen.getByRole('button', { name: '의견서 작성' }));
    expect(screen.getByRole('heading', { name: '완성한 입지 심의 의견서' })).toBeInTheDocument();
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(0);
    await user.click(screen.getByLabelText('선택안의 근거'));
    await user.keyboard('{End} 수정');
    expect(screen.queryByRole('heading', { name: '완성한 입지 심의 의견서' })).not.toBeInTheDocument();
    expect(document.querySelectorAll('.gi-pulse')).toHaveLength(1);
    await user.click(screen.getByRole('button', { name: '의견서 작성' }));
    expect(screen.getByRole('heading', { name: '완성한 입지 심의 의견서' })).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: '처음부터 다시 시작' }));
    expect(screen.getByRole('combobox', { name: '미션 선택' })).toHaveValue('');
    expect(screen.queryByRole('heading', { name: '완성한 입지 심의 의견서' })).not.toBeInTheDocument();
  });
});
